cargo-features = ["resolver"]

[workspace]
members = [
    "auction",
    "authority",
    "bencher",
    "benchmarking",
    "currencies",
    "gradually-update",
    "oracle",
    "oracle/rpc",
    "oracle/rpc/runtime-api",
    "tokens",
    "traits",
    "utilities",
    "vesting",
    "rewards",
    "nft",
    "xcm",
    "xtokens",
    "xcm-support",
    "unknown-tokens",
    "build-script-utils",
    "weight-gen",
    "weight-meter",
]
resolver = "2"

[profile.dev]
split-debuginfo = "unpacked"

[patch.'https://github.com/paritytech/substrate']
frame-benchmarking = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
frame-support = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
frame-system = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
pallet-authority-discovery = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
pallet-authorship = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
pallet-balances = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
pallet-elections-phragmen = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
pallet-offences = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
pallet-scheduler = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
pallet-session = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
pallet-staking = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
pallet-timestamp = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
pallet-treasury = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
pallet-vesting = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sc-client-api = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sc-client-db = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sc-executor = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sc-executor-common = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sc-executor-wasmi = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-api = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-application-crypto = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-arithmetic = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-authority-discovery = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-authorship = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-blockchain = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-consensus = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-core = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-debug-derive = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-externalities = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-inherents = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-io = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-keystore = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-npos-elections = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-npos-elections-compact = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-panic-handler = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-runtime = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-runtime-interface = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-session = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-staking = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-state-machine = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-std = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-storage = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-tasks = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-timestamp = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-trie = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-version = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-wasm-interface = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }
sp-utils = { git = "https://github.com/paritytech//substrate", rev = "57346f6b24875f8935280dba51fa8ab0a9ba1e39" }

[patch.'https://github.com/paritytech/cumulus']
cumulus-primitives-core = { git = "https://github.com/paritytech//cumulus", rev = "fd80849dde5c209c20a996cfcc5aaacd4666dcbe" }
parachain-info = { git = "https://github.com/paritytech//cumulus", rev = "fd80849dde5c209c20a996cfcc5aaacd4666dcbe" }

[patch.'https://github.com/paritytech/polkadot']
xcm = { git = "https://github.com/paritytech//polkadot", rev = "bfd38ed620458fcf57eb5cde8b5732368c19b714" }
xcm-executor = { git = "https://github.com/paritytech//polkadot", rev = "bfd38ed620458fcf57eb5cde8b5732368c19b714" }
xcm-builder = { git = "https://github.com/paritytech//polkadot", rev = "bfd38ed620458fcf57eb5cde8b5732368c19b714" }
pallet-xcm = { git = "https://github.com/paritytech//polkadot", rev = "bfd38ed620458fcf57eb5cde8b5732368c19b714" }
polkadot-core-primitives = { git = "https://github.com/paritytech//polkadot", rev = "bfd38ed620458fcf57eb5cde8b5732368c19b714" }
polkadot-runtime-parachains = { git = "https://github.com/paritytech//polkadot", rev = "bfd38ed620458fcf57eb5cde8b5732368c19b714" }
polkadot-parachain = { git = "https://github.com/paritytech//polkadot", rev = "bfd38ed620458fcf57eb5cde8b5732368c19b714" }
polkadot-primitives = { git = "https://github.com/paritytech//polkadot", rev = "bfd38ed620458fcf57eb5cde8b5732368c19b714" }
